name: test
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  dart_serial_port: ^0.1.0-nullsafety.0
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
